name: Persistent Bot Runner

on:
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق (يمكن تعديله حسب الحاجة)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Cache dependencies for faster builds
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Stop old bot processes
      - name: Stop old bot processes
        run: |
          pkill -9 -f "python aflamya.py" || true

      # Step 6: Run the bot in the background
      - name: Run the bot
        run: |
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          nohup python aflamya.py > bot.log 2>&1 &

      # Step 7: Keep the job alive
      - name: Keep the job running
        run: |
          echo "Bot is running. Keeping the job alive..."
          sleep 300  # الحفاظ على المهمة حية لمدة 5 دقائق
